// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	Uuid           pgtype.UUID      `json:"uuid"`
	PassportNumber string           `json:"passport_number"`
	Surname        string           `json:"surname"`
	Name           string           `json:"name"`
	Patronymic     pgtype.Text      `json:"patronymic"`
	Address        string           `json:"address"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}
